# CHKDSK Archivo NLS Espa¤ol
# Set 1: Par metros e Inicio
1.1:Par metros no v lidos (escriba %c? para ayuda)\n
1.2:Por favor especifique una ruta despu‚s de /d\n
1.3:­%s reservado para uso futuro!
1.4:­Opci¢n desconocida %s utilizada!
1.5:­Estas opciones no se pueden combinar!\n
1.6:No se puede acceder a %s\n
1.7:No se puede obtener el directorio actual\n
1.8:Especificaci¢n de unidad no v lida\n
1.9:Ruta relativa incorrecta\n

# Set 2: Errores T‚cnicos
2.1:FAT32 no soportado actualmente\n
2.2:Problema al imprimir los factores de desfragmentaci¢n.\n
2.3:Descriptor sospechoso en el sector de arranque (¨2.88 MB?)\n
2.4:Los sectores BOOT son diferentes\n
2.5:Problema leyendo sector(es) de arranque\n
2.6:Las tablas FAT son diferentes\n
2.7:Problema leyendo tabla(s) FAT\n
2.8:\nProblema escaneando la superficie\n
2.9:Error accediendo al volumen\n
2.10:\nSe encontraron errores. No utiliz¢ la opci¢n /F. Los errores no se corregir n.\n\n

# Set 3: Uso / Estado
3.1:Comprueba un volumen y muestra un informe de estado\nUso:\n\tChkdsk [<volumen>] [%cf] [%cd <archivos>] [%cr] [%cs] [%cv]\n\n%cf: Intenta corregir los errores encontrados.\n%cd: Muestra los archivos indicados y su fragmentaci¢n.\n%cr: Escanea la superficie e intenta recuperar datos legibles.\n%cs: Muestra solo el resumen.\n%cv: Muestra los nombres de archivo durante la comprobaci¢n.\n\nNota: Si se omite el volumen, se asume la unidad actual.\n
3.2:Tiempo transcurrido: %lds\n

# Set 4: Resumen del volumen
4.1:No se puede obtener informaci¢n del resumen\n
4.2:La etiqueta del volumen es 
4.3: creado el 
4.4:El n£mero de serie del disco es %04X-%04X\n
4.5:KB de espacio total en disco\n
4.6:bytes de espacio total en disco\n
4.7:KB en un total de %lu archivos
4.8:bytes en un total de %lu archivos
4.9:KB en %lu archivos ocultos
4.10:bytes en %lu archivos ocultos
4.11:KB en %lu archivos de sistema
4.12:bytes en %lu archivos de sistema
4.13:KB en %lu directorios
4.14:bytes en %lu directorios
4.15:KB tama¤o total de archivos
4.16:bytes tama¤o total de archivos
4.17:KB disponibles en el volumen
4.18:bytes disponibles en el volumen
4.19:bytes en cada cl£ster
4.20:n£mero total de cl£steres
4.21:n£mero de cl£steres defectuosos
4.22:n£mero de cl£steres libres
4.23:\nHubo un problema obteniendo informaci¢n del disco, el resumen puede ser incorrecto\n

# Set 5: An lisis de superficie
5.1:Escaneando, por favor espere . . .\n
5.2:\nError de medio en sector %lu, reubicando . . .\n
5.3:­No hay espacio libre para reubicar el cl£ster!\n

# Set 7: Archivos cruzados
7.1:Espacio en disco insuficiente para desdoblar cl£steres cruzados\n
7.2:%s tiene enlaces cruzados (cross-linked)\n
